call UPDATE_PROJECTS_JAVA.bat
call UPDATE_TESTS_JAVA.bat
call UPDATE_TOOLS_JAVA.bat

call UPDATE_EXAMPLES_PY.bat
call UPDATE_MobileAPP.bat
call UPDATE_PATTERN_PY.bat
call UPDATE_PROJECTS_PY.bat
call UPDATE_TEST_PY.bat
call UPDATE_TESTS_PY.bat
call UPDATE_TOOLS_PY.bat
call UPDATE_YOUTUBE.bat
